---
core:
  # server_url: https://<SPACE>.kinops.io  OR https://<SERVER_NAME>.com/kinetic/<SPACE_SLUG>
  server_url: ${serverURL}
  old_space_slug: <SPACE_SLUG>
  space_slug: ${slugName}
  space_name: ${spaceName}
  service_user_username: ${serviceUsername}
  service_user_password: ${servicePassword}
options:
  delete: false
task:
  # server_url: https://<SPACE>.kinops.io/app/components/task   OR https://<SERVER_NAME>.com/kinetic-task
  server_url: ${serverURL}/kinetic-task
  service_user_username: ${serviceUsername}
  service_user_password: ${servicePassword}
http_options:
  log_level: info
  log_output: stderr
