---
core:
  server_url: ${serverURL}
  space_slug: "${slugName}"
  space_name: "${spaceName}"
  service_user_username: "${serviceUsername}"
  service_user_password: "${servicePassword}"
options:
  SUBMISSIONS_TO_EXPORT:
    - datastore:
      formSlug:
    - datastore:
      kappSlug:
      formSlug:
  REMOVE_DATA_PROPERTIES:
    - createdAt
    - createdBy
    - updatedAt
    - updatedBy
    - closedAt
    - closedBy
    - submittedAt
    - submittedBy
    - id
    - authStrategy
    - key
    - handle
task:
  server_url: "${serverURL}/kinetic-task"
  service_user_username: "${serviceUsername}"
  service_user_password: "${servicePassword}"
http_options:
  log_level: info
  log_output: stderr
